const actionTypes = {
  GET_TRENDING_LIST: 'GET_TRENDING_LIST',
  GET_TRENDING_LIST_LOADING: 'GET_TRENDING_LIST_LOADING',
  GET_TRENDING_LIST_ERROR: 'GET_TRENDING_LIST_ERROR'
};

export default actionTypes;
