const actionTypes = {
  GET_MOVIES_BY_FILTERS: 'GET_MOVIES_BY_FILTERS',
  GET_MOVIES_BY_FILTERS_LOADING: 'GET_MOVIES_BY_FILTERS_LOADING',
  GET_MOVIES_BY_FILTERS_ERROR: 'GET_MOVIES_BY_FILTERS_ERROR'
};

export default actionTypes;
