const actionTypes = {
  GET_MOVIES_BY_GENRE_ID: 'GET_MOVIES_BY_GENRE_ID',
  GET_MOVIES_BY_GENRE_ID_ERROR: 'GET_MOVIES_BY_GENRE_ID_ERROR',
  GET_MOVIES_BY_GENRE_ID_LOADING: 'GET_MOVIES_BY_GENRE_ID_LOADING'
};

export default actionTypes;
