const actionTypes = {
  GET_TRENDING_ITEM_DATA: 'GET_TRENDING_ITEM_DATA',
  GET_TRENDING_ITEM_LOADING: 'GET_TRENDING_ITEM_LOADING',
  GET_TRENDING_ITEM_ERROR: 'GET_TRENDING_ITEM_ERROR'
};

export default actionTypes;
