const firebaseTypes = {
  SET_USER_DATA: "SET_USER_DATA",
  SET_USER_SIGNIN: "SET_USER_SIGNIN",
  GET_BOOKMARKS: "GET_BOOKMARKS",
  DELETE_BOOKMARK: "DELETE_BOOKMARK",
  SET_BOOKMARKS_LOADING: "SET_BOOKMARKS_LOADING",
};

export default firebaseTypes;
