const GlobalActionTypes = {
  GET_TRENDING_LIST: 'GET_TRENDING_LIST',
  GET_TRENDING_ERROR: 'GET_TRENDING_ERROR',
  SET_LOADING: 'SET_LOADING',
  GET_TRENDING_ITEM_DATA: 'GET_TRENDING_ITEM_DATA',
  GET_ERROR: 'GET_ERROR',
  //media
  GET_MOVIE: 'GET_MOVIE',
  GET_GENRE_MOVIES: 'GET_GENRE_MOVIES',
  GET_GENRE_LIST: 'GET_GENRE_LIST',
  GET_CAST: 'GET_CAST',
  GET_PERSON: 'GET_PERSON',
  GET_PHOTO: 'GET_PHOTO',
  GET_TRENDING: 'GET_TRENDING',
  TRENDING_GET_DATA: 'TRENDING_GET_DATA',
  SET_LOADING: 'SET_LOADING',
  SEARCH_MOVIES: 'SEARCH_MOVIES',
  FILTER_MOVIES: 'FILTER_MOVIES'
};

export default GlobalActionTypes;
