const GlobalActionTypes = {
  GET_TRENDING_LIST: 'GET_TRENDING_LIST',
  GET_TRENDING_ERROR: 'GET_TRENDING_ERROR',
  SET_LOADING: 'SET_LOADING',
  GET_TRENDING_ITEM_DATA: 'GET_TRENDING_ITEM_DATA',
  GET_ERROR: 'GET_ERROR',
  GOT_ERROR: 'GOT_ERROR',
  //media
  GET_TRAILER: 'GET_TRAILER',
  GET_MOVIE_DATA: 'GET_MOVIE_DATA',
  GET_MOVIES_BY_GENRE_ID: 'GET_MOVIES_BY_GENRE_ID',
  GET_GENRE_LIST: 'GET_GENRE_LIST',
  GET_CAST: 'GET_CAST',
  GET_PERSON: 'GET_PERSON',
  GET_PERSON_PHOTOS: 'GET_PERSON_PHOTOS',
  GET_TRENDING: 'GET_TRENDING',
  TRENDING_GET_DATA: 'TRENDING_GET_DATA',
  SET_LOADING: 'SET_LOADING',
  SEARCH_MOVIES: 'SEARCH_MOVIES',
  GET_MOVIES_BY_FILTERS: 'GET_MOVIES_BY_FILTERS'
};

export default GlobalActionTypes;
