const GlobalActionTypes = {
  GET_TRENDING_LIST: 'GET_TRENDING_LIST',
  GET_TRENDING_ERROR: 'GET_TRENDING_ERROR',
  SET_LOADING: 'SET_LOADING',
  GET_TRENDING_ITEM_DATA: 'GET_TRENDING_ITEM_DATA'
};

export default GlobalActionTypes;
