const actionTypes = {
  GET_PERSON_PHOTOS: 'GET_PERSON_PHOTOS',
  GET_PERSON_PHOTOS_LOADING: 'GET_PERSON_PHOTOS_LOADING',
  GET_PERSON_PHOTOS_ERROR: 'GET_PERSON_PHOTOS_ERROR'
};

export default actionTypes;
